# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: tianhaoz95/desktop-ros-docker-image:kinetic

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo/src

    steps:
      - checkout

      - run:
          name: install python dependencies
          command: |
            pip install -r requirements.txt

      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: check native pip packages
          command: |
            pip list

      - run:
          name: test build
          command: |
            cd ~/repo
            catkin_make

      - store_artifacts:
          path: test-reports
          destination: test-reports
